#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import sys
import os
from send_speech import Stt

currentDir = os.path.dirname(os.path.realpath(__file__))

while True:
    if os.path.isfile(currentDir + '/Microphone/pycmd_nocmd'):
        # The -l option doesn't cut the sound
        # 0.1% is really to low, when I just touch the keyboard it
        # recognizes it as a sound.
        os.system("rec -r 16000 -b 16 speech.flac silence -l 1 0.1 8% 1 2.0 6%")
        with open('speech.flac', 'r') as audio_file:
            content = audio_file.read()
        audio_file.closed

        stt = Stt()
        text = stt.speech_to_text(content)
        if text:
	        print 'Out:',text.encode('utf-8').strip()
	        os.system(currentDir + "/recognize \"" + text.encode('utf-8').strip() + "\"")
        else:
            print 'No text was returned'
