#!/bin/bash

echo "Setting up your user account."

mkdir $HOME/.leopold/
touch $HOME/.leopold/UserInfo

echo "I will need your personal information to create your account."
echo -n "Enter your first name [ENTER]: "
read firstName
echo -n "Enter your last name [ENTER]: "
read lastName
echo -n "Enter your email [ENTER]: "
read email
echo -n "Enter your language (en=English) [ENTER]: "
read lang

echo "Saving user."

cp Recognition/config/BlankInfo $HOME/.leopold/UserInfo
cat > $HOME/.leopold/UserInfo << EOL
FIRST=${firstName}
LAST=${lastName}
EMAIL=${email}
LANGUAGE=${lang}
EOL

